---
- name: Prepare nodes for Kubernetes cluster
  hosts: all
  become: true
  roles:
    - os_prep

- name: Initialize cluster
  hosts: all
  become: true
  roles:
    - k8s_setup

- name: Deploy apps
  hosts: all
  become: true
  roles:
    - app_deploy
