---
- name: Add ArgoCD repo
  kubernetes.core.helm_repository:
    name: argocd
    repo_url: "https://argoproj.github.io/argo-helm"
  delegate_to: localhost
  become: false

- name: Install ArgoCD with helm
  kubernetes.core.helm:
    name: argocd
    chart_ref: argocd/argo-cd
    chart_version: "{{ argocd_version }}"
    release_namespace: argocd
    create_namespace: true
    values:
      configs:
        params:
          server.insecure: true
      server:
        ingress:
          enabled: false
          ingressClassName: traefik
          hosts:
            - argocd.kube
          tls:
            - hosts:
                - argocd.kube
              secretName: argocd-tls
    kubeconfig: ~/.kube/config
    atomic: true
    wait: true
  delegate_to: localhost
  become: false

- name: Create ArgoCD IngressRoute
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    state: present
    definition:
      apiVersion: traefik.io/v1alpha1
      kind: IngressRoute
      metadata:
        name: argocd-server
        namespace: argocd
      spec:
        entryPoints:
          - websecure
        routes:
          - kind: Rule
            match: Host(`argocd.kube`)
            priority: 10
            services:
              - name: argocd-server
                port: 80
        tls:
          certResolver: default
  delegate_to: localhost
  become: false

- name: Check if root Application exists
  kubernetes.core.k8s_info:
    kubeconfig: ~/.kube/config
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: root
    namespace: argocd
  register: root_app
  delegate_to: localhost
  become: false

- name: Bootstrap root Application
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    state: present
    template: root-application.yml.j2
  delegate_to: localhost
  become: false
  when: root_app.resources | length == 0