---
- name: Install and configure MetalLB
  ansible.builtin.import_tasks: metallb.yml
  tags: metallb

- name: Install and configure Traefik
  ansible.builtin.import_tasks: ingress.yml
  tags: traefik
