---
- name: Install and configure MetalLB
  ansible.builtin.import_tasks: metallb.yml
  tags: metallb

- name: Install and configure Traefik
  ansible.builtin.import_tasks: ingress.yml
  tags: traefik

- name: Install and configure Cert-Manager
  ansible.builtin.import_tasks: certmgr.yml
  tags: certmgr

- name: Install and configure ArgoCD
  ansible.builtin.import_tasks: argocd.yml
  tags: argocd
