---
- name: Add MetalLB repo
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: "https://metallb.github.io/metallb"
  delegate_to: localhost
  become: false

- name: Install MetalLB with helm
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    chart_version: "0.16.1"
    release_namespace: metallb-system
    create_namespace: true
    kubeconfig: ~/.kube/config
    atomic: true
    wait: true
  delegate_to: localhost
  become: false

- name: Configure MetalLB IP pool
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: home-pool
        namespace: metallb-system
      spec:
        addresses:
          - 192.168.1.200-192.168.1.220
  delegate_to: localhost
  run_once: true
  become: false

- name: Configure L2Advertisement
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: home-pool
        namespace: metallb-system
      spec: {}
  delegate_to: localhost
  run_once: true
  become: false
