---
- name: Install packages on all nodes
  ansible.builtin.include_tasks: install.yml
  tags: install

- name: Initialize cluster
  ansible.builtin.include_tasks: master.yml
  tags: init
  when: inventory_hostname in groups['control_plane']

- name: Connect worker nodes
  ansible.builtin.include_tasks: workers.yml
  tags: workers
  when: inventory_hostname in groups['workers']
