---
- name: Check for presented kubeadm config
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_init_check

- name: Initialize cluster
  ansible.builtin.shell: kubeadm init --pod-network-cidr={{ cidr_network }}
  become: true
  changed_when: true
  when: not kubeadm_init_check.stat.exists

- name: Create .kube directory for user
  ansible.builtin.file:
    path: "{{ k8s_control_home }}/.kube"
    state: directory
    mode: "0755"
    owner: "{{ k8s_control_user }}"
    group: "{{ k8s_control_user }}"

- name: Copy admin.conf
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ k8s_control_home }}/.kube/config"
    remote_src: true
    mode: "0600"
    owner: "{{ k8s_control_user }}"
    group: "{{ k8s_control_user }}"

- name: Download Flannel CNI manifest
  ansible.builtin.get_url:
    url: "{{ flannel_url }}"
    dest: /tmp/kube-flannel.yml
    mode: "0644"
    force: true
  register: flannel_download

- name: Deploy Flannel CNI
  ansible.builtin.command: kubectl apply -f /tmp/kube-flannel.yml
  environment:
    KUBECONFIG: "{{ k8s_control_home }}/.kube/config"
  become: false
  register: flannel_apply
  changed_when: >
    'created' in flannel_apply.stdout or
    'configured' in flannel_apply.stdout
  when: flannel_download.changed

- name: Get connection command for workers
  ansible.builtin.shell: kubeadm token create --print-join-command
  changed_when: false
  register: join_command
  no_log: true

- name: Save connection command
  ansible.builtin.set_fact:
    k8s_join_cmd: "{{ join_command.stdout }}"
