---
- name: Check if node is already in cluster
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_check

- name: Join worker node to cluster
  ansible.builtin.command: >-
    {{ hostvars[groups['control_plane'][0]]['k8s_join_cmd'] }}
  become: true
  changed_when: true
  when: not kubelet_check.stat.exists
  no_log: true
