---
- name: Load variables
  ansible.builtin.include_vars: vars.yml

- name: Create DB secret
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    state: present
    template: apps/netcourse/db/templates/secret.yml.j2
  delegate_to: localhost

- name: Deploy PostgreSQL
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    state: present
    template: apps/netcourse/db/templates/statefulset.yml.j2
  delegate_to: localhost

- name: Expose PostgreSQL service
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    state: present
    template: apps/netcourse/db/templates/service.yml.j2
  delegate_to: localhost