---
# Prerequisites:
#   kubectl create secret docker-registry ghcr-pull -n netcourse \
#     --docker-server=ghcr.io \
#     --docker-username=hadcrab \
#     --docker-password=<github-token>

- name: Load variables
  ansible.builtin.include_vars: vars.yml

- name: Create namespace
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ app_namespace }}"
  delegate_to: localhost
  become: false

- name: Deploy frontend
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    state: present
    template: apps/netcourse/frontend/templates/deployment.yml.j2
  delegate_to: localhost
  become: false

- name: Expose frontend
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    state: present
    template: apps/netcourse/frontend/templates/ingress.yml.j2
  delegate_to: localhost
  become: false

- name: Deploy frontend service
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    state: present
    template: apps/netcourse/frontend/templates/service.yml.j2
  delegate_to: localhost
  become: false